### ISSUE TITLE
Temporary Instance IP addresses

### ISSUE THREAD

**Issue by HTenkanen** [Python-for-geo-people/Course-information#7]
Hi all @Python-for-geo-people/fall2016 

here you can find temporary computer instance IP addresses:

**VOL 1 for VUOKKO:** 
86.50.168.141
86.50.170.125 
86.50.170.101
86.50.170.47
86.50.168.207

**REST WILL BE ADDED SOON!** 

**VOL 2 for JORINA:**

86.50.170.92
86.50.168.13
86.50.169.218
86.50.170.118
86.50.168.170

**VOL 3 extra instances if needed**

86.50.170.87
86.50.169.220
86.50.168.15
86.50.170.56
86.50.170.124

**VOL 4 extra instances if needed**

86.50.170.5
86.50.170.49
86.50.170.122
86.50.170.115
86.50.170.120

**Comment by VuokkoH** [comment]
Thanks!

Otherwise ok

86.50.168.207
86.50.170.101

were occupied by a geologist

**Comment by VuokkoH** [comment]
so we need one more

**Comment by HTenkanen** [comment]
I now added more up there. Try to distribute them in a locigal manner

**Comment by HTenkanen** [comment]
Or at least in such a manner that two students wouldn't work on the same instance 😄

**Comment by HTenkanen** [comment]
Sorry for this again guys. CSC updated their IP-tables which is the reason for these malfunctions. I try to fix this now.

**Comment by HTenkanen** [comment]
@jorina If you need more instances, just say, and I will create more.

**Comment by jorina** [comment]
ok vuokko occupies 86.50.170.92

**Comment by jorina** [comment]
we need 7 more, thanks

**Comment by HTenkanen** [comment]
Hi @jorina, I just added fiver for you. Will still do the rest

**Comment by jorina** [comment]
thats enough. where do I find them? :/

**Comment by HTenkanen** [comment]
I updated the first message (above)

**Comment by jorina** [comment]
ok. can you give us two more? then we are happy (for now)

**Comment by jorina** [comment]
Kiitos !!!

**Comment by HTenkanen** [comment]
@jorina I added five more on top.

**Comment by HTenkanen** [comment]
@jorina @VuokkoH 

Could you say to your students that they would **memorialize what was their IP address**, since I will keep those instances running until the Dashboard system is stable again. Thus, they can continue working with their instance as long as the system is fixed.

**Comment by HTenkanen** [comment]
Hi all @Python-for-geo-people/fall2016 

Now the pb.geo.helsinki.fi site is working again and you can launch instances from there. I will however, continue checking this thing now to make sure that this thing won't come back together with CSC. Thus, there might be some breakages on the website but I will send you a notice of those, if they happen.

**Comment by HTenkanen** [comment]
Hi all @Python-for-geo-people/fall2016,

as the system is now up and running I will destroy the temporary instances that I launched earlier today. 

**I HOPE EVERYBODY HAS SAVED THEIR WORK FROM THOSE INSTANCES!!!**

**IF YOU HAVEN'T SAVED YOUR WORK, DO IT ASAP OR SEND ME A MESSAGE SO I WON'T DESTROY IT BEFORE YOU HAVE SAVED THE WORK!**

Cheers,
Henrikki

**Comment by HTenkanen** [comment]
Hi all @Python-for-geo-people/fall2016,

argh! It seems that the system went down again. I am so sorry for this. This is getting slightly annoying for me as well. 

I will launch those instances mentioned in the first post again, and you can use them. Please use only **a single instance and remember the one that you are using!** Add some kind of note to the terminal **who you are** and that the instance is taken when you reserve it. **Still remember to always save your work to GitHub!! ** I will keep those instances available until further notice.

**Comment by HTenkanen** [comment]
@Python-for-geo-people/fall2016

okey guys, now all those IP addresses that are mentioned at the top of this page are instances that you can use for your work. 

I will keep them running until further notice. The problem that we have with the Pouta Dashboard interface seem to be more tricky than it previously looked. I try to find a fix for it ASAP. 

**NOW IT IS IMPORTANT TO UNDERSTAND THAT THE INSTANCES ARE NOT SECURE!** So please, be careful when using them and please do not log into any of your personal accounts from those instances (other than GitHub). If you need to read e.g. email, do it on your local machine. This is due to the fact that, anyone can now access those instances if they just know the IP address. 

**Few instructions on current instances**

1. Try to use the same instance always (keep track on what IP address you used) 
2. **Save your work to GitHub in a similar manner as before!**
3. When you have finished working, CLEAN THE INSTANCE --> 
   - Shut down Spyder, 
   - **SIGN OUT FROM GITHUB** (or others might be able to access your account)
   - **SIGN OUT FROM ANY OTHER PLACES WHERE YOU HAVE LOGGED IN!!**
   - Remove unnecessary files from the /home/geo folder so that it is clean for next "possible customer"

Again, sorry for this hassle. If you have any questions or comments, please add a comment below. 

Best,
Henrikki

**Comment by HTenkanen** [comment]
Dear all @Python-for-geo-people/fall2016 

Now the system is up and running again at [https://pb.geo.helsinki.fi](https://pb.geo.helsinki.fi).

I would like for you to help me and try again to launch instances from that site in a similar manner as always. If you face any problems with accessing the instance or the web page, I would really REALLY appreciate if you would report those problems under here as a comment. That would help me to keep track if any new problems come up. 

Because the system has been unstable, I will still keep those instances running that are listed on top of this page. If any problems comes with the website or launching the instance from there, you can always use these ones listed here. Still, I would like that you first try to launch the computer from our website (it's  also way more secure because no-one else can access your instance) and hence help me out tracking that everything works. 

Hopefully this is now solved. Fingers crossed. 

Best,
Henrikki

**Comment by HTenkanen** [comment]
Hi all @Python-for-geo-people/fall2016 ,

now the system has been stable the whole day, and we figured out with CSC what was the reason for the instability. Thus, **I will SHUTDOWN those running instances mentioned on top of this page** at 21:00. Thus, if you are working there, save your work, and start using our Pouta Blueprints website as usual to access the cloud computers. 

Best,
Henrikki

**Comment by davewhipp** [comment]
Hi @HTenkanen. Thanks for taking care of this mess. Very good to hear that things may be working as they have been now.

**Comment by HTenkanen** [comment]
As things are stable, I'll close this issue now.
